version: "3.3"

services:
  web:
    build: .
    # command: gunicorn ocommerce.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment:
      - ENV=Production
